import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Fragment_Mono, Playfair_Display } from "next/font/google";
import clsx from "clsx";
import ThemeProvider, { Theme } from "../context/ThemeProvider";
import { cookies } from "next/headers";
import { neueMontreal } from "../assets/fonts/fonts";

const fragmentMono = Fragment_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-fragment-mono",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const savedTheme = (await cookies()).get("color-theme")?.value;
  const theme: Theme =
    savedTheme === "light" || savedTheme === "dark" ? savedTheme : "dark";
  return (
    <html
      lang="en"
      className={clsx(
        theme,
        "overflow-hidden antialiased",
        neueMontreal.variable,
        fragmentMono.variable,
        playfairDisplay.variable,
      )}
      data-color-theme={theme}
    >
      <body suppressHydrationWarning>
        <ThemeProvider initialTheme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
