import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Fragment_Mono } from "next/font/google";
import clsx from "clsx";
import ThemeProvider, { Theme } from "../context/ThemeProvider";
import { cookies } from "next/headers";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });
const fragmentMono = Fragment_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const savedTheme = (await cookies()).get("color-theme")?.value;
  const theme: Theme =
    savedTheme === "light" || savedTheme === "dark" ? savedTheme : "dark";
  return (
    <html
      lang="en"
      className={clsx(
        theme,
        "overflow-hidden antialiased",
        geist.variable,
        fragmentMono.variable,
      )}
      data-color-theme={theme}
    >
      <body suppressHydrationWarning>
        <ThemeProvider initialTheme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
