// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Block struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	Type      string
	Content   string
	X         int32
	Y         int32
	W         int32
	H         int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type Session struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Space struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
