// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (id, user_id, name, slug)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, slug, created_at, updated_at
`

type CreateSpaceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
	Slug   string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Slug,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks
WHERE id = $1 AND space_id = $2
`

type DeleteBlockParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, arg.ID, arg.SpaceID)
	return err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces
WHERE slug = $1 AND user_id = $2
`

type DeleteSpaceParams struct {
	Slug   string
	UserID uuid.UUID
}

func (q *Queries) DeleteSpace(ctx context.Context, arg DeleteSpaceParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpace, arg.Slug, arg.UserID)
	return err
}

const getBlocksBySpaceID = `-- name: GetBlocksBySpaceID :many
SELECT id, space_id, type, content, x, y, w, h, created_at, updated_at FROM blocks
WHERE space_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetBlocksBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getBlocksBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Type,
			&i.Content,
			&i.X,
			&i.Y,
			&i.W,
			&i.H,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpaceBySlug = `-- name: GetSpaceBySlug :one
SELECT id, user_id, name, slug, created_at, updated_at FROM spaces
WHERE slug = $1 AND user_id = $2
`

type GetSpaceBySlugParams struct {
	Slug   string
	UserID uuid.UUID
}

func (q *Queries) GetSpaceBySlug(ctx context.Context, arg GetSpaceBySlugParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceBySlug, arg.Slug, arg.UserID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, user_id, name, slug, created_at, updated_at FROM spaces
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSpaces(ctx context.Context, userID uuid.UUID) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpaceName = `-- name: UpdateSpaceName :exec
UPDATE spaces
SET name = $1, updated_at = NOW()
WHERE slug = $2 AND user_id = $3
`

type UpdateSpaceNameParams struct {
	Name   string
	Slug   string
	UserID uuid.UUID
}

func (q *Queries) UpdateSpaceName(ctx context.Context, arg UpdateSpaceNameParams) error {
	_, err := q.db.ExecContext(ctx, updateSpaceName, arg.Name, arg.Slug, arg.UserID)
	return err
}

const upsertBlock = `-- name: UpsertBlock :exec
INSERT INTO blocks (id, space_id, type, content, x, y, w, h)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    content    = EXCLUDED.content,
    x          = EXCLUDED.x,
    y          = EXCLUDED.y,
    w          = EXCLUDED.w,
    h          = EXCLUDED.h,
    updated_at = NOW()
`

type UpsertBlockParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
	Type    string
	Content string
	X       int32
	Y       int32
	W       int32
	H       int32
}

func (q *Queries) UpsertBlock(ctx context.Context, arg UpsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlock,
		arg.ID,
		arg.SpaceID,
		arg.Type,
		arg.Content,
		arg.X,
		arg.Y,
		arg.W,
		arg.H,
	)
	return err
}
