// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (id, user_id, name, slug, description, icon_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, slug, created_at, updated_at, description, icon_url
`

type CreateSpaceParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	IconUrl     string    `json:"icon_url"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IconUrl,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.IconUrl,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :execrows
DELETE FROM blocks
WHERE id = $1 AND space_id = $2
`

type DeleteBlockParams struct {
	ID      uuid.UUID `json:"id"`
	SpaceID uuid.UUID `json:"space_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBlock, arg.ID, arg.SpaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSpace = `-- name: DeleteSpace :execrows
DELETE FROM spaces
WHERE slug = $1 AND user_id = $2
`

type DeleteSpaceParams struct {
	Slug   string    `json:"slug"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSpace(ctx context.Context, arg DeleteSpaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSpace, arg.Slug, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBlocksBySpaceID = `-- name: GetBlocksBySpaceID :many
SELECT id, space_id, type, content, x, y, w, h, created_at, updated_at FROM blocks
WHERE space_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetBlocksBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getBlocksBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Type,
			&i.Content,
			&i.X,
			&i.Y,
			&i.W,
			&i.H,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpaceBySlug = `-- name: GetSpaceBySlug :one
SELECT id, user_id, name, slug, created_at, updated_at, description, icon_url FROM spaces
WHERE slug = $1 AND user_id = $2
`

type GetSpaceBySlugParams struct {
	Slug   string    `json:"slug"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSpaceBySlug(ctx context.Context, arg GetSpaceBySlugParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceBySlug, arg.Slug, arg.UserID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.IconUrl,
	)
	return i, err
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, user_id, name, slug, created_at, updated_at, description, icon_url FROM spaces
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSpaces(ctx context.Context, userID uuid.UUID) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpaceName = `-- name: UpdateSpaceName :execrows
UPDATE spaces
SET name = $1, description = $2, icon_url = $3, updated_at = NOW()
WHERE slug = $4 AND user_id = $5
`

type UpdateSpaceNameParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IconUrl     string    `json:"icon_url"`
	Slug        string    `json:"slug"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateSpaceName(ctx context.Context, arg UpdateSpaceNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSpaceName,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.Slug,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertBlock = `-- name: UpsertBlock :exec
INSERT INTO blocks (id, space_id, type, content, x, y, w, h)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    content    = EXCLUDED.content,
    x          = EXCLUDED.x,
    y          = EXCLUDED.y,
    w          = EXCLUDED.w,
    h          = EXCLUDED.h,
    updated_at = NOW()
`

type UpsertBlockParams struct {
	ID      uuid.UUID `json:"id"`
	SpaceID uuid.UUID `json:"space_id"`
	Type    string    `json:"type"`
	Content string    `json:"content"`
	X       int32     `json:"x"`
	Y       int32     `json:"y"`
	W       int32     `json:"w"`
	H       int32     `json:"h"`
}

func (q *Queries) UpsertBlock(ctx context.Context, arg UpsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlock,
		arg.ID,
		arg.SpaceID,
		arg.Type,
		arg.Content,
		arg.X,
		arg.Y,
		arg.W,
		arg.H,
	)
	return err
}
