// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE lower(username) = lower($1)) AS exists
`

func (q *Queries) CheckUsernameExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUsernameExists, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (id, email, username, provider, provider_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, created_at, username, provider, provider_id
`

type CreateOAuthUserParams struct {
	ID         uuid.UUID      `json:"id"`
	Email      string         `json:"email"`
	Username   string         `json:"username"`
	Provider   string         `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createOAuthUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Provider,
		arg.ProviderID,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, username)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, created_at, username, provider, provider_id
`

type CreateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Username     string         `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, username, provider, provider_id FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, username, provider, provider_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT id, email, password_hash, created_at, username, provider, provider_id FROM users
WHERE provider = $1
  AND provider_id = $2
LIMIT 1
`

type GetUserByProviderIDParams struct {
	Provider   string         `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderID, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, password_hash, created_at, username, provider, provider_id FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash sql.NullString `json:"password_hash"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
